# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Botinfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bot', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('describe', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contentgroupofbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cont_group', models.CharField(default='', max_length=200)),
                ('id_group_in_ss', models.CharField(default='', max_length=20)),
                ('describe', models.CharField(default='', max_length=20)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='botinfos',
            name='country_of_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Countries'),
        ),
    ]
