# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlesonothersitemonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_article', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Articlesonothersitemonitoringdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_monitoring', models.DateTimeField(default=django.utils.timezone.now)),
                ('count_of_views', models.CharField(default='', max_length=200)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Articlesonothersitemonitoring')),
            ],
        ),
        migrations.CreateModel(
            name='Contentwebsiteofbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cont_site', models.CharField(default='', max_length=200)),
                ('adres_page_to_content_link', models.CharField(default='', max_length=20)),
                ('describe', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dataofbots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_friends', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dataofoungroupofbots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_friends', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Oungroupofbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cont_group', models.CharField(default='', max_length=200)),
                ('id_group_in_ss', models.CharField(default='', max_length=20)),
                ('describe', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Spreadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('spread_link', models.CharField(default='', max_length=200)),
                ('spread_img', models.CharField(default='', max_length=200)),
                ('spread_text', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Spreadatainfomonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadinf_comment', models.CharField(default='', max_length=3)),
                ('spreadinf_likes', models.CharField(default='', max_length=3)),
                ('spreadinf_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_spread_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Spreadata')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe_thesis', models.CharField(default='', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Typeofsocialnetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_country', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='botinfos',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='botinfos',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='botinfos',
            name='login',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contentgroupofbot',
            name='describe',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='thesis',
            name='bot_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='country_of_thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Countries'),
        ),
        migrations.AddField(
            model_name='spreadata',
            name='botwhopost',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='spreadata',
            name='thesis',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Thesis'),
        ),
        migrations.AddField(
            model_name='oungroupofbot',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='dataofoungroupofbots',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Oungroupofbot'),
        ),
        migrations.AddField(
            model_name='dataofbots',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='contentwebsiteofbot',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='articlesonothersitemonitoring',
            name='bot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='articlesonothersitemonitoring',
            name='httpadres_of_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netoko.Spreadata'),
        ),
        migrations.AddField(
            model_name='botinfos',
            name='type_of_bot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Typeofsocialnetwork'),
        ),
    ]
