# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0004_auto_20170317_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botinfos',
            name='type_of_social_net',
            field=models.CharField(default='', max_length=20),
        ),
    ]
