# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0005_auto_20170317_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoringbotonline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('describe', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Monitoringbotonlinedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
