# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0008_auto_20170320_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historypublishtobotandgroupsfromsiteandgroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_link', models.CharField(default='', max_length=200)),
                ('name_of_bot_or_group', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
