# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0010_searchopengroupinvk'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchopengroupinvk',
            name='min_count_of_people',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='searchopengroupinvk',
            name='name_of_group',
            field=models.CharField(default='', max_length=50),
        ),
    ]
