# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0011_auto_20170321_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysisofaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_account', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
