# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0012_analysisofaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='oungroupofbot',
            name='type_of_social_net',
            field=models.CharField(default='', max_length=20),
        ),
    ]
