# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0013_oungroupofbot_type_of_social_net'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataofbots',
            name='date_mark',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dataofoungroupofbots',
            name='date_mark',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
