# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0015_spreadata_typess'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadata',
            name='groups_to_spread',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
