# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0016_spreadata_groups_to_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadatainfomonitoring',
            name='bot_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AddField(
            model_name='spreadatainfomonitoring',
            name='type_of_social_net',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Typeofsocialnetwork'),
        ),
        migrations.AlterField(
            model_name='oungroupofbot',
            name='bot_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfos'),
        ),
        migrations.AlterField(
            model_name='oungroupofbot',
            name='type_of_social_net',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Typeofsocialnetwork'),
        ),
    ]
