# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0019_remove_botinfos_city_of_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinfos',
            name='city_of_bot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='netoko.Cities'),
            preserve_default=False,
        ),
    ]
