# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0020_botinfos_city_of_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='name_of_country',
        ),
        migrations.AddField(
            model_name='cities',
            name='name_of_city',
            field=models.CharField(default='', max_length=50),
        ),
    ]
