# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0021_auto_20170322_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botinfos',
            name='city_of_bot',
        ),
    ]
