# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0022_remove_botinfos_city_of_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botinfos',
            name='created_date',
        ),
        migrations.AddField(
            model_name='botinfos',
            name='city_of_bot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Cities'),
        ),
        migrations.AlterField(
            model_name='botinfos',
            name='country_of_bot',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Countries'),
        ),
    ]
