# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0023_auto_20170322_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinfos',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
