# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0024_botinfos_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgroupofbot',
            name='type_of_social_net',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Typeofsocialnetwork'),
        ),
    ]
