# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0026_auto_20170323_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botinfos',
            old_name='country_of_bot',
            new_name='country_of_bot_id',
        ),
    ]
