# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0031_auto_20170412_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settingsanswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
