# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0032_settingsanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='botinfosindiffrentsocnet',
            name='auto_pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='netoko.Settingsanswers'),
        ),
    ]
