# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netoko', '0033_botinfosindiffrentsocnet_auto_pilot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentgroupofbot',
            name='bot_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='netoko.Botinfosindiffrentsocnet'),
        ),
    ]
