# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sendingletters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(default='', max_length=5000, null=True)),
                ('subject_message', models.CharField(default='', max_length=500, null=True)),
                ('date_message', models.DateTimeField(default=django.utils.timezone.now)),
                ('success_message', models.CharField(default='', max_length=5, null=True)),
            ],
            options={
                'verbose_name_plural': 'Таблица отправленных e-mail',
            },
        ),
        migrations.CreateModel(
            name='Tableofresources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=200, null=True)),
                ('e_mail', models.CharField(default='', max_length=50, null=True)),
                ('describe', models.CharField(default='', max_length=1000, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('surname', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Таблица e-mail адресов редакторов сайтов и администраторов групп в соцсетях',
            },
        ),
        migrations.AddField(
            model_name='sendingletters',
            name='target',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Tableofresources'),
        ),
    ]
