# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tableofounemails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='', max_length=200, null=True)),
                ('e_mail', models.CharField(default='', max_length=50, null=True)),
                ('describe', models.CharField(default='', max_length=1000, null=True)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('surname', models.CharField(default='', max_length=50, null=True)),
                ('password', models.CharField(default='', max_length=50, null=True)),
                ('login', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Таблица почтовых ящиков, принадлежащих 67 зданию',
            },
        ),
    ]
