# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0002_tableofounemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingletters',
            name='is_rain_letter',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
