# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0003_sendingletters_is_rain_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yesno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(default='', max_length=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Да/Нет',
            },
        ),
        migrations.AddField(
            model_name='tableofounemails',
            name='test_email',
            field=models.CharField(default='', max_length=3, null=True),
        ),
    ]
