# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0004_auto_20170417_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofounemails',
            name='test_email',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Yesno'),
        ),
    ]
