# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0006_whoarewe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofounemails',
            name='organization_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Whoarewe'),
        ),
    ]
