# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0007_auto_20170418_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableofounemails',
            name='login',
        ),
        migrations.AlterField(
            model_name='tableofounemails',
            name='organization_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Whoarewe'),
        ),
    ]
