# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0011_auto_20170418_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingletters',
            name='is_rain_letter',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Yesno'),
        ),
    ]
