# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0012_auto_20170418_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendingletters',
            name='subject_message',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sendingletters',
            name='text_message',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tableofounemails',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tableofounemails',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tableofounemails',
            name='organization_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Whoarewe'),
        ),
        migrations.AlterField(
            model_name='tableofounemails',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tableofresources',
            name='describe',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tableofresources',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tableofresources',
            name='organization_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='postman.Whoarethey'),
        ),
        migrations.AlterField(
            model_name='tableofresources',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
