# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0013_auto_20170425_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableofounemails',
            name='phone_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
