# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postman', '0014_tableofounemails_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tableofounemails',
            options={'verbose_name_plural': 'Таблица почтовых ящиков отправителя'},
        ),
        migrations.RemoveField(
            model_name='tableofounemails',
            name='test_email',
        ),
        migrations.RemoveField(
            model_name='tableofresources',
            name='test_email',
        ),
    ]
